# Generated by Django 4.2.7 on 2025-11-27 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('rotten', 'Rotten')], max_length=10)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(upload_to='scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
