# Generated by Django 4.2.7 on 2025-11-28 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_user_scanresult_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('storage_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='scanner.user')),
            ],
            options={
                'verbose_name': 'Crop Batch',
                'verbose_name_plural': 'Crop Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
